In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans

In [2]:
df1 = pd.read_csv("Country-data.csv")
df2 = pd.read_csv("creditcard.csv")

In [3]:
df1.head()

country  child_mort  exports  health  imports  income  \
0          Afghanistan        90.2     10.0    7.58     44.9    1610   
1              Albania        16.6     28.0    6.55     48.6    9930   
2              Algeria        27.3     38.4    4.17     31.4   12900   
3               Angola       119.0     62.3    2.85     42.9    5900   
4  Antigua and Barbuda        10.3     45.5    6.03     58.9   19100   

   inflation  life_expec  total_fer   gdpp  
0       9.44        56.2       5.82    553  
1       4.49        76.3       1.65   4090  
2      16.10        76.5       2.89   4460  
3      22.40        60.1       6.16   3530  
4       1.44        76.8       2.13  12200

In [4]:
df2.head()

Time        V1        V2        V3        V4        V5        V6        V7  \
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9  ...       V21       V22       V23       V24       V25  \
0  0.098698  0.363787  ... -0.018307  0.277838 -0.110474  0.066928  0.128539   
1  0.085102 -0.255425  ... -0.225775 -0.638672  0.101288 -0.339846  0.167170   
2  0.247676 -1.514654  ...  0.247998  0.771679  0.909412 -0.689281 -0.327642   
3  0.377436 -1.387024  ... -0.108300  0.005274 -0.190321 -1.175575  0.647376   
4 -0.270533  0.817739  ... -0.009431  0.798278 -0.137458  0.141267 -0.206010   

        V26       V27       V28  Amount  Class  
0 -0.189115  0.133558 -0.021053  149.62      0  
1  0.125895 -0.008983  0.014724    2.69      0  
2 -0.139097 -0.055353 -0.059752  378.66      0  
3 -0.221929  0.062723  0.061458  123.50      0  
4  0.502292  0.219422  0.215153   69.99      0  

[5 rows x 31 columns]

In [5]:
np.unique(df2["Class"].values)

array([0, 1], dtype=int64)

In [6]:
df11 = df2[df2.columns[1:]]
df21 = df2[df2.columns[:-1]]

In [7]:
X1 = df11.values
X2 = df21.values

In [8]:
X1.shape, X2.shape

((284807, 30), (284807, 30))

Country data for k=2

In [9]:
model = KMeans(n_clusters=2, n_init=4, verbose=1, max_iter=3)

In [10]:
model.fit(X1)

Initialization complete
Iteration 0, inertia 8974711044.464308
Iteration 1, inertia 8846032840.929388
Iteration 2, inertia 8821990489.99287
Initialization complete
Iteration 0, inertia 9763383147.96573
Iteration 1, inertia 8985768733.560263
Iteration 2, inertia 8901645271.894714
Initialization complete
Iteration 0, inertia 14712058996.861246
Iteration 1, inertia 13075293337.448517
Iteration 2, inertia 11757774119.850487
Initialization complete
Iteration 0, inertia 11247517739.036726
Iteration 1, inertia 10539915537.287617
Iteration 2, inertia 9969364040.235285


KMeans(max_iter=3, n_clusters=2, n_init=4, verbose=1)

In [11]:
model.cluster_centers_

array([[ 4.69632267e-02,  9.05244035e-02,  3.60661045e-02,
        -1.55643947e-02,  5.16650346e-02, -2.72812858e-02,
        -5.19119660e-02,  1.36870799e-02,  5.08582685e-03,
         1.18901148e-02, -2.54196889e-04,  1.22487494e-03,
         1.12668721e-04, -4.46069321e-03,  1.07453493e-03,
         7.50620168e-05, -1.18080217e-03, -1.48480944e-03,
         4.49115197e-03, -3.23329347e-02, -8.99978478e-03,
         6.48709300e-03,  7.04924314e-03, -5.31200229e-04,
         2.73845245e-03, -4.29137423e-04, -1.80220819e-04,
        -1.16168780e-03,  6.20311957e+01,  1.67918882e-03],
       [-2.14537503e+00, -4.13533755e+00, -1.64757248e+00,
         7.11012978e-01, -2.36016311e+00,  1.24626422e+00,
         2.37144343e+00, -6.25253447e-01, -2.32330841e-01,
        -5.43164452e-01,  1.16122272e-02, -5.59547607e-02,
        -5.14693468e-03,  2.03773473e-01, -4.90869257e-02,
        -3.42898450e-03,  5.39414278e-02,  6.78290936e-02,
        -2.05164891e-01,  1.47703375e+00,  4.11128342e-

In [12]:
model.inertia_

8808663541.007402

In [13]:
model = KMeans(n_clusters=2, n_init=4, verbose=1, max_iter=3)
model.fit(X2)

Initialization complete
Iteration 0, inertia 125682923173285.62
Iteration 1, inertia 118320270466488.2
Converged at iteration 1: center shift 1187.4050037793224 within tolerance 7517.262262351321.
Initialization complete
Iteration 0, inertia 150296733853086.0
Iteration 1, inertia 118369518348097.33
Iteration 2, inertia 118321325558829.89
Initialization complete
Iteration 0, inertia 184216389259341.75
Iteration 1, inertia 118969819333841.34
Iteration 2, inertia 118324953954741.34
Initialization complete
Iteration 0, inertia 169400627983405.97
Iteration 1, inertia 118399235688978.17
Iteration 2, inertia 118320841892019.52
Converged at iteration 2: center shift 4745.861859614324 within tolerance 7517.262262351321.


KMeans(max_iter=3, n_clusters=2, n_init=4, verbose=1)

In [14]:
model.cluster_centers_

array([[ 1.41080701e+05,  2.73826415e-01, -5.15359421e-02,
        -7.06911786e-01, -1.55088721e-01,  2.79408760e-01,
        -8.09538313e-02,  1.21047307e-01, -6.12746712e-02,
         4.04616187e-02,  3.45121186e-02, -2.43834471e-01,
         3.76187226e-02, -3.36832850e-02, -6.54156813e-02,
        -2.12089846e-01,  1.38009807e-02, -5.10221131e-02,
         8.25261414e-02,  2.46478504e-02, -4.59814507e-02,
         4.32967620e-02,  1.27673120e-01,  3.32659374e-02,
        -1.36156327e-02, -1.35720516e-01, -2.67101515e-02,
        -2.18711670e-03, -3.32285703e-03,  8.80007217e+01],
       [ 5.50501966e+04, -2.35337900e-01,  4.42921491e-02,
         6.07549623e-01,  1.33289748e-01, -2.40135601e-01,
         6.95751162e-02, -1.04033130e-01,  5.26620210e-02,
        -3.47744113e-02, -2.96611615e-02,  2.09561566e-01,
        -3.23311072e-02,  2.89488272e-02,  5.62209787e-02,
         1.82278905e-01, -1.18611414e-02,  4.38505428e-02,
        -7.09264254e-02, -2.11833959e-02,  3.95183862e-

In [15]:
model.inertia_

118320091408059.06

Country Data for k=5

In [16]:
model = KMeans(n_clusters=5, n_init=4, verbose=1, max_iter=3)
model.fit(X1)

Initialization complete
Iteration 0, inertia 3503839349.1048403
Iteration 1, inertia 2741991913.9281845
Iteration 2, inertia 2598413840.9780498
Initialization complete
Iteration 0, inertia 3975797782.839267
Iteration 1, inertia 2773258694.3507123
Iteration 2, inertia 2758452222.599601
Initialization complete
Iteration 0, inertia 2673714958.6006618
Iteration 1, inertia 2539438045.1760864
Iteration 2, inertia 2535129475.516436
Initialization complete
Iteration 0, inertia 3199140339.7991977
Iteration 1, inertia 2659891401.4953012
Iteration 2, inertia 2589332635.754554


KMeans(max_iter=3, n_clusters=5, n_init=4, verbose=1)

In [17]:
model.cluster_centers_

array([[-4.73846026e-01, -1.37179875e+00, -2.43429373e-01,
         4.16193433e-02, -6.37220185e-01,  3.11216178e-01,
         3.23059604e-01, -1.10669817e-01, -3.11335435e-02,
        -1.25325310e-01, -4.90461897e-02,  4.64579692e-02,
        -4.76652805e-02,  6.04209288e-03, -7.85697385e-02,
        -1.66622885e-01,  2.94364476e-02,  7.57746337e-02,
        -4.64260707e-02,  2.62454413e-01,  9.18500833e-02,
         3.48921713e-02,  1.02138224e-02, -2.28998337e-02,
         3.24868812e-03,  1.71750765e-02, -2.41911345e-02,
         4.45990216e-03,  3.55806187e+02,  2.73462270e-03],
       [ 9.31574875e-02,  2.23232506e-01,  5.98642278e-02,
        -1.94002642e-02,  1.13510035e-01, -5.75403139e-02,
        -8.34506344e-02,  2.46355860e-02,  8.06542400e-03,
         2.38467285e-02,  4.23170129e-03, -3.32369341e-03,
         4.58787483e-03, -5.03701886e-03,  8.42378536e-03,
         1.57786844e-02, -4.00109230e-03, -8.83047920e-03,
         8.95498655e-03, -5.73737451e-02, -1.79939858e-

In [18]:
model.inertia_

2528696369.03016